### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by anithaguna** [Koutoulakis/Deep-Learning-for-Human-Activity-Recognition#2]
I got this error when i run the CNN file by gait dataset

segmenting signal...
Traceback (most recent call last):
  File "C:\Users\ADMIN\gaitdap\ModelCreation\CNN\cnn1d.py", line 209, in <module>
    train_x, train_y = segment_dap(x_train,y_train,input_width)
  File "C:\Users\ADMIN\gaitdap\ModelCreation\CNN\cnn1d.py", line 63, in segment_dap
    if(int(len(x_train[start:end])) == window_size):
TypeError: slice indices must be integers or None or have an __index__ method

please tell me how to solve it

**Comment by nattafahhm** [comment]
@anithaguna How can you solve this issue?
